environment_name: 'LunarLander-v3'
agent:
  type: 'DQN'
  hyperparameters:
    learning_rate: 0.001
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay: 0.995

    replay_buffer_size: 10000
    target_update_frequency: 10
    batch_size: 64

    network_architecture:
      - type: 'Linear'
        out_features: 64
      - type: 'ReLU'
      - type: 'Linear'
        out_features: 64
      - type: 'ReLU'

training:
  num_episodes: 1000
logging:
  wandb_project: 'rl-algos'
  use_wandb: false
  verbose: 10

  show_episode: true
  video_dir: 'logs/lunarlander/dqn'
  save_video_frequency: 50
